### PR TITLE
Spa fixes

### PR DESCRIPTION
**Pull request by mora145**

### CODE REVIEW

**Comment by rwpsychology** [comment]
...Is "burgermeister" REALLY the German word for "mayor"?

**Comment by mora145** [comment]
I don't know German.

**Comment by rwpsychology** [comment]
Sorry, commented on the wrong PR.

**Comment by rwpsychology** [comment]
Just a heads up: many of these translations are no longer current due to the fact that "HIS" etc. have been replaced by "[NAME_possessive]" etc., so they will no longer work.

**Pull request merged**
