### PR TITLE
Update to Japanese strings

### PR DESCRIPTION
**Pull request by HG-Dev**
Confirmed to produce no warnings/errors. The ramblings could be improved, but I'll need some outside input first.

### CODE REVIEW

**Comment by HG-Dev** [comment]
I found a warning hiding amongst others...
`Def-linked translation error: Found no Verse.Room named Office to match Office.label`
Still trying to figure out what's the problem.

**Comment by HG-Dev** [comment]
Found the problem (folder name). This request can now be satisfactorily merged.

**Comment by rwpsychology** [comment]
Just a heads up: many of these translations are no longer current due to the fact that "HIS" etc. have been replaced by "[NAME_possessive]" etc., so they will no longer work.

**Comment by HG-Dev** [comment]
Thanks for the heads up. I'm not entirely prepared to go through the testing rigmarole on B19, but I'm getting there. Looking forward to see how Psychology meshes with the updated social interaction system!

**Pull request merged**
